#!/usr/bin/env python3
"""Render `kb.py due --json` output as a GitHub issue title + body.

    python3 scripts/kb_due_issue.py [due.json]   # reads stdin if no path given

Pure formatting, no GitHub calls — the workflow that owns opening, updating,
and closing the issue is `.github/workflows/kb-due.yml`; it shells out to
`gh issue create`/`edit`/`close` and only needs this script's title/body.
Kept separate so the formatting logic can be unit tested without mocking a
network call.

No third-party dependencies — stdlib only, same as the rest of the KB tooling.
"""
import json
import sys

ISSUE_TITLE = "Knowledge base: entries coming due"


def render(rows):
    """rows: kb.due_report()'s shape. Returns (title, body)."""
    lines = [
        "Prospective entries whose `due:` date has passed or falls within the "
        "checked window. Act on each, then `kb.py set <name> due YYYY-MM-DD` "
        "(or `kb.py rm <name>`) to clear it.",
        "",
    ]
    for r in rows:
        flag = "**OVERDUE**" if r["overdue"] else f"in {r['days']}d"
        lines.append(f"- [ ] `{r['name']}` — due {r['due']} ({flag}) — {r['description']}")
    lines.append("")
    lines.append(
        "_Generated by `kb.py due`; this issue is opened, updated, or closed "
        "automatically by the `kb-due` workflow — editing it by hand will be "
        "overwritten on the next run._"
    )
    return ISSUE_TITLE, "\n".join(lines)


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else None
    with (open(path) if path else sys.stdin) as f:
        rows = json.load(f)
    title, body = render(rows)
    print(json.dumps({"title": title, "body": body, "count": len(rows)}))


if __name__ == "__main__":
    main()
