#!/usr/bin/env python3
"""Visualization layer: regenerates .kb/generated/graph.mmd (Mermaid).

Nodes are colored by memory type; a subtle marker denotes confidence.
Edges come from each entry's `links:` frontmatter field.
"""
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from kb import KB_DIR, TYPES, iter_entries, parse_frontmatter  # noqa: E402

OUT = KB_DIR / "generated" / "graph.mmd"
OUT_MD = KB_DIR / "generated" / "graph.md"
OUT_INDEX = KB_DIR / "generated" / "index.md"

TYPE_CLASS = {
    "semantic": "semantic",
    "episodic": "episodic",
    "procedural": "procedural",
    "working": "working",
    "retrieval": "retrieval",
    "parametric": "parametric",
    "prospective": "prospective",
}

CLASS_DEFS = """
    classDef semantic fill:#2e7d32,color:#fff
    classDef episodic fill:#1565c0,color:#fff
    classDef procedural fill:#6a1b9a,color:#fff
    classDef working fill:#8d6e63,color:#fff
    classDef retrieval fill:#00838f,color:#fff
    classDef parametric fill:#455a64,color:#fff
    classDef prospective fill:#ef6c00,color:#fff
""".strip("\n")


def node_id(name: str) -> str:
    return "n_" + re.sub(r"[^a-zA-Z0-9_]", "_", name)


def _read_frontmatter(path):
    try:
        return parse_frontmatter(path)
    except OSError as e:
        print(f"warning: skipping {path}: {e}", file=sys.stderr)
        return None


def main():
    entries = list(iter_entries())
    lines = ["flowchart LR", CLASS_DEFS]

    names = set()
    node_lines = []
    edge_lines = []
    parsed = []

    for t, path in entries:
        fm_body = _read_frontmatter(path)
        if fm_body is None:
            continue
        fm, _ = fm_body
        parsed.append((t, path, fm))
        name = fm.get("name", path.stem)
        names.add(name)
        conf = fm.get("confidence", "unverified")
        label = f"{name}<br/>({conf})"
        node_lines.append(f'    {node_id(name)}["{label}"]:::{TYPE_CLASS[t]}')

    for t, path, fm in parsed:
        name = fm.get("name", path.stem)
        links = fm.get("links") or []
        if not isinstance(links, list):
            print(f"warning: {path}: 'links' must be a list, got {links!r}", file=sys.stderr)
            continue
        for link in links:
            if link in names:
                edge_lines.append(f"    {node_id(name)} --> {node_id(link)}")

    lines.extend(node_lines)
    lines.extend(edge_lines)

    if not entries:
        lines.append('    empty["(no entries yet — run kb.py new)"]')

    graph = "\n".join(lines) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(graph, encoding="utf-8")

    md = (
        "# Memory graph\n\n"
        "Auto-generated by `scripts/visualize.py` — do not edit by hand.\n\n"
        f"```mermaid\n{graph}```\n"
    )
    OUT_MD.write_text(md, encoding="utf-8")

    write_index(parsed)

    print(f"wrote {OUT} and {OUT_MD} ({len(entries)} entries, {len(edge_lines)} links)")


def write_index(parsed):
    by_type = {t: [] for t in TYPES}
    for t, path, fm in parsed:
        by_type[t].append(fm)

    lines = [
        "# Memory index",
        "",
        "Auto-generated by `scripts/visualize.py` — do not edit by hand.",
        "",
    ]
    for t in TYPES:
        fms = by_type[t]
        if not fms:
            continue
        lines.append(f"## {t}")
        lines.append("")
        for fm in fms:
            name = fm.get("name", "?")
            desc = fm.get("description", "")
            lines.append(f"- `{name}` — {desc}")
        lines.append("")

    OUT_INDEX.parent.mkdir(parents=True, exist_ok=True)
    OUT_INDEX.write_text("\n".join(lines).rstrip("\n") + "\n")


if __name__ == "__main__":
    main()
